[package]
name = "opendaemon"
authors = ["OpenDaemon contributors"]
version = "0.1.0"
edition = "2024"

exclude = [
    "e2e/**",
    ".github/**",
    ".vscode/**",
    ".pytest_cache/**",
    "target/**",
]


[dependencies]
anyhow = "1"
axum = "0.8"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }



[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"



# only works with cargo-release
[package.metadata.release]
pre-release-replacements = [
    # Update inline-table dependency snippets like:
    # opendaemon = { version = "0.2", features = ["custom"] }
    { file = "README.md", search = "opendaemon\\s*=\\s*\\{\\s*version\\s*=\\s*\"[0-9]+\\.[0-9]+(\\.[0-9]+)?(-[0-9A-Za-z.-]+)?\"", replace = "opendaemon = { version = \"{{version}}\"" },
    # Update plain dependency snippets like:
    # opendaemon = "0.2"
    { file = "README.md", search = "opendaemon\\s*=\\s*\"[0-9]+\\.[0-9]+(\\.[0-9]+)?(-[0-9A-Za-z.-]+)?\"", replace = "opendaemon = \"{{version}}\"", min = 0 },
]
